version: "3.8"

services:
  prompt-mcp-server:
    build:
      context: ../McpServer
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - /workspace/node_modules
    working_dir: /workspace
    command: sleep infinity
    ports:
      - "8547:3000"
    environment:
      - NODE_ENV=development
